# Generated by Django 6.0.4 on 2026-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='hours',
        ),
        migrations.AddField(
            model_name='workday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
