# Generated by Django 6.0.4 on 2026-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_workday_hours_workday_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.FloatField(default=100),
        ),
    ]
